spring:
  application:
    name: ms-usuario
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3308/ms_usuario
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
